# Render.com deployment configuration
services:
  - type: web
    name: ipswich-retail
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      python manage.py populate_store
      gunicorn --bind 0.0.0.0:$PORT --workers 3 ipswich_retail.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ipswich-retail-db
          property: connectionString

  - type: redis
    name: ipswich-retail-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: ipswich-retail-db
    databaseName: ipswich_retail
    user: ipswich_user
    region: oregon
    plan: starter